# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ui_emulator.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Emulator(object):
    def setupUi(self, Emulator):
        Emulator.setObjectName("Emulator")
        Emulator.setEnabled(True)
        Emulator.resize(355, 355)
        Emulator.setWindowTitle("")
        Emulator.setAnimated(True)
        Emulator.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(Emulator)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.connectionBox = QtWidgets.QHBoxLayout()
        self.connectionBox.setObjectName("connectionBox")
        self.addressInput = QtWidgets.QLineEdit(self.centralwidget)
        self.addressInput.setMinimumSize(QtCore.QSize(100, 0))
        self.addressInput.setMaximumSize(QtCore.QSize(220, 16777215))
        self.addressInput.setMaxLength(45)
        self.addressInput.setObjectName("addressInput")
        self.connectionBox.addWidget(self.addressInput)
        self.portInput = QtWidgets.QLineEdit(self.centralwidget)
        self.portInput.setMinimumSize(QtCore.QSize(50, 0))
        self.portInput.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portInput.setMaxLength(10)
        self.portInput.setObjectName("portInput")
        self.connectionBox.addWidget(self.portInput)
        self.connectBtn = QtWidgets.QPushButton(self.centralwidget)
        self.connectBtn.setEnabled(True)
        self.connectBtn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.connectBtn.setObjectName("connectBtn")
        self.connectionBox.addWidget(self.connectBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.connectionBox.addItem(spacerItem)
        self.verticalLayout.addLayout(self.connectionBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        Emulator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Emulator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 355, 22))
        self.menubar.setObjectName("menubar")
        Emulator.setMenuBar(self.menubar)

        self.retranslateUi(Emulator)
        QtCore.QMetaObject.connectSlotsByName(Emulator)

    def retranslateUi(self, Emulator):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Emulator", "Connection Details"))
        self.addressInput.setText(_translate("Emulator", "localhost"))
        self.addressInput.setPlaceholderText(_translate("Emulator", "Address"))
        self.portInput.setText(_translate("Emulator", "7005"))
        self.portInput.setPlaceholderText(_translate("Emulator", "Port"))
        self.connectBtn.setText(_translate("Emulator", "Start Server"))
        self.label_2.setText(_translate("Emulator", "Bit Error Rate (BER)"))
        self.label_3.setText(_translate("Emulator", "Delay Per Packet"))

